export const talks = [
  {
    year: "2020",
    talks: [
      {
        title: "Testing Web Accessibility",
        conference: "DevTalks Romania",
        date: "Jun 2020",
        location: "Bucharest, Romania",
        link: "https://www.devtalks.ro/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "UXDX Vienna",
        date: "Jun 2020",
        location: "Vienna, Austria [Online]",
        link: "https://uxdxconf.com/vienna",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "Pick JS",
        date: "May 2020",
        location: "Katowice, Poland [Online]",
        link: "https://pickjs.com/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "JSDay Spain 2020",
        date: "May 2020",
        location: "Madrid, Spain",
        link: "http://jsday.es/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      /*
      {
        title: "Testing Web Accessibility",
        conference: "New Devs On The Block",
        date: "Apr 2020",
        location: "Vienna, Austria",
        link: "https://newdevs.org/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      */
      {
        title: "Testing Web Accessibility",
        conference: "StayAtHome Conf",
        date: "Mar 2020",
        location: "[Online]",
        link: "https://www.stayathomeconf.com/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "FrontConf",
        date: "Mar 2020",
        location: "Munich, Germany [Online]",
        link: "https://frontconf.com/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "A11y Club Berlin",
        date: "Mar 2020",
        location: "Berlin, Germany [Online]",
        link: "https://a11y-meetup-berlin.de/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Accessibility in Web Development",
        conference: "UpLeveled (Workshop)",
        date: "Mar 2020",
        location: "Vienna, Austria",
        link: "https://upleveled.io/",
        video: "",
        slides:
          "https://speakerdeck.com/bolonio/accessibility-in-web-development",
      },
      {
        title: "Testing Web Accessibility",
        conference: "Vienna JS",
        date: "Feb 2020",
        location: "Vienna, Austria",
        link: "https://viennajs.org/en/meetup/2020-02",
        video: "https://www.youtube.com/watch?v=ZupKHcb9w-k",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "TestBustersNight Vienna",
        date: "Jan 2020",
        location: "Vienna, Austria",
        link: "https://www.meetup.com/Agile-Test-Automation-Meetup-VIENNA",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Diversity Pannel",
        conference: "SQLSaturday (Diversity Pannel)",
        date: "Jan 2020",
        location: "Vienna, Austria",
        link: "https://www.sqlsaturday.com/917/EventHome.aspx",
        video: "",
        slides: "",
      },
    ],
  },
  {
    year: "2019",
    talks: [
      {
        title: "Testing Web Accessibility",
        conference: "Heisenbug Conf",
        date: "Dec 2019",
        location: "Moscow, Russia",
        link: "https://heisenbug-moscow.ru/en/",
        video: "https://www.youtube.com/watch?v=GyXkH5ZmSfk",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "DevFest Siberia",
        date: "Dec 2019",
        location: "Novosibirsk, Russia",
        link: "https://gdg-siberia.com/",
        video: "https://www.youtube.com/watch?v=1eDCdL-3uI0",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "Developer Melange",
        date: "Dec 2019",
        location: "Podcast",
        link: "https://developermelange.github.io/",
        video: "",
        slides: "",
      },
      {
        title: "Testing Web Accessibility",
        conference: "WebClerks",
        date: "Nov 2019",
        location: "Vienna, Austria",
        link: "https://webclerks.at/",
        video: "https://youtu.be/ucLEMETfrTA?t=14220",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "DevFest Vienna",
        date: "Nov 2019",
        location: "Vienna, Austria",
        link: "https://devfest.at/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "React Vienna",
        date: "Nov 2019",
        location: "Vienna, Austria",
        link: "https://twitter.com/reactvienna",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "JSConf Colombia",
        date: "Oct 2019",
        location: "Medellín, Colombia",
        link: "http://jsconf.co/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "AXSChat",
        date: "Oct 2019",
        location: "YouTube",
        link: "http://axschat.com/",
        video: "https://www.youtube.com/watch?v=JFaS1JGO71w",
        slides: "",
      },
      {
        title: "Testing Web Accessibility",
        conference: "UpLeveled (Workshop)",
        date: "Oct 2019",
        location: "Vienna, Austria",
        link: "https://upleveled.io/",
        video: "",
        slides:
          "https://speakerdeck.com/bolonio/accessibility-in-web-development",
      },
      {
        title: "Testing Web Accessibility",
        conference: "Accessibility talks",
        date: "Aug 2019",
        location: "YouTube",
        link: "https://www.youtube.com/c/accessibilitytalks",
        video: "https://www.youtube.com/watch?v=Nq6UhL_QvZk",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
    ],
  },
  {
    year: "2018",
    talks: [
      {
        title: "How does your website 'sound' like?",
        conference: "UX Vienna",
        date: "Dec 2018",
        location: "Vienna, Austria",
        link: "https://uxvienna.at/",
        video: "",
        slides:
          "https://speakerdeck.com/bolonio/how-does-your-website-sound-like",
      },
      {
        title: "How does your website 'sound' like?",
        conference: "DevFest Vienna",
        date: "Nov 2018",
        location: "Vienna, Austria",
        link: "https://devfest.at/",
        video: "https://www.youtube.com/watch?v=yKYA-7tczuk",
        slides:
          "https://speakerdeck.com/bolonio/how-does-your-website-sound-like",
      },
      {
        title: "Willhaben Markup Language WHML",
        conference: "Vienna JS",
        date: "May 2018",
        location: "Vienna, Austria",
        link: "https://viennajs.org/",
        video: "https://www.youtube.com/watch?v=tJXzyHHh4pc",
        slides:
          "https://speakerdeck.com/bolonio/willhaben-markup-language-whml",
      },
    ],
  },
  {
    year: "2017",
    talks: [
      {
        title: "Dark Patterns - User Interfaces Designed to Trick People",
        conference: "UX Vienna",
        date: "Nov 2017",
        location: "Vienna, Austria",
        link: "https://uxvienna.at/",
        video: "",
        slides: "http://slides.com/adrianbolonio/darkpatterns-uxvienna#/",
      },
    ],
  },
]
